from app.models.user import User
from app.models.area import Area
from app.models.resident import Resident
from app.models.municipal_administrator import MunicipalAdministrator
from app.models.maintenance_team import MaintenanceTeam
from app.models.it_staff import ITStaff
from app.models.fault_report import FaultReport
from app.models.photo import Photo
from app.models.report_history import ReportHistory
from app.models.maintenance_assignment import MaintenanceAssignment
from app.models.outage_schedule import OutageSchedule
from app.models.audit_log import AuditLog
from app.models.bug_report import BugReport